# Generated by Django 6.0.4 on 2026-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sharee', 'Sharee'), ('Kurti', 'Kurti'), ('Skirt Top', 'Skirt Top'), ('Plazzo Top', 'Plazzo Top'), ('Cord Set', 'Cord Set'), ('Biyer Kulo', 'Biyer Kulo'), ('Biyer Mukut', 'Biyer Mukut'), ('Gachkouto', 'Gachkouto')], max_length=50),
        ),
    ]
